# Generated by Django 4.2.7 on 2023-11-26 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_orderitem_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippinPrice',
            new_name='shippingPrice',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='countary',
            new_name='country',
        ),
    ]
